# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

h = np.array(height)
w = np.array(weight)

bmi = w / (h**2) * 730
print(bmi)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [14]:
import random
# Example makeMatrix(param1,param2) -- Extra params can be added here as well

def makeMatrix(low,high):
    
    low = int(lo)
    high = int(h)
    Matrix = np.random.randint(low, high, size=(3,3))
    print(Matrix)
    pass

lo = input("Enter a integer that will be the lowest number for the matrix: ")
h = input("Enter a integer that will be the highest number for the matrix: ")
makeMatrix(lo, h)

Enter a integer that will be the lowest number for the matrix: 1
Enter a integer that will be the highest number for the matrix: 10
[[3 9 7]
 [8 7 3]
 [6 5 7]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [31]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, skip_header = 1,
                        usecols = np.arange(0, 24), invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

brs2017 = load_data('redsox_2017_hitting.txt')
brs2018 = load_data('redsox_2018_hitting.txt')


"Boston 2017 had more SLG in 2017"

def betterYear():
    SLG2017 = np.average(brs2017['SLG'])
    SLG2018 = np.average(brs2018['SLG'])
    if SLG2017 > SLG2018:
        SLGperc = 100-((SLG2018/SLG2017)*100)
        print(f"Boston 2017 had more SLg in 2017.\n{SLGperc}%")
    elif SLG2018 > SLG2017:
        SLGperc = 100-((SLG2017/SLG2018)*100)
        print(f"Boston 2018 had more SLg in 2018.\n{SLGperc}%")
    else:
        print(f"Boston 2017 and 2018 had a SLG of: {SLGperc}%")
        
betterYear()

Boston 2017 had more SLg in 2017.
1.4866828918457031%
